name: make_sha256_pack
on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main
jobs:
  sha256:
    name: sha256
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create nro sha256
        run: |
          git pull
          curl -sL "${{ github.server_url }}/${{ github.repository }}/raw/main/switch/AIO_LS_pack_Updater/AIO_LS_pack_Updater.nro" | shasum -a 256 | cut -d " " -f 1 > sha256_AIO_LS_pack_Updater.txt
      - name: push changes
        run: |
          git config --global user.name 'shadow2560_bot'
          git config --global user.email '24191064+shadow2560@users.noreply.github.com'
          CHANGED=$(git diff --name-only)
          git add .
          if [[ `git status --porcelain` ]]; then
            git commit -m "automatic: Mise à jour du sha256 de AIO_LS_pack_Updater"
            git push
          else
            echo "Nothing to commit!"
          fi
          git pull
          echo New SHA256 of the pack: 
          curl -sL "https://github.com/shadow2560/switch_AIO_LS_pack/archive/refs/heads/main.zip" | shasum -a 256 | cut -d " " -f 1