name: make_sha256_pack
on:
  push:
    branches:
      - main
    paths-ignore:
      - '/readme.md'
      - '/nettoyage_sd.bat'
      - '/.github/**'
      - '/.gitignore'
      - '/switch/AIO_LS_pack_Updater/AIO_LS_pack_Updater.nro'
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '/readme.md'
      - '/nettoyage_sd.bat'
      - '/.github/**'
      - '/.gitignore'
      - '/switch/AIO_LS_pack_Updater/AIO_LS_pack_Updater.nro'
jobs:
  sha256:
    name: sha256
    runs-on: ubuntu-latest
    steps:
      - name: Create zip sha256
        run: |
          echo New SHA256 of the pack: 
          curl -sL "https://github.com/shadow2560/switch_AIO_LS_pack/archive/refs/heads/main.zip" | shasum -a 256 | cut -d " " -f 1
          # curl -sL "${{ github.server_url }}/${{ github.repository }}/archive/refs/heads/main.zip" | shasum -a 256 | cut -d " " -f 1